### ISSUE TITLE
API Gateway Tech Spec

### ISSUE THREAD

**Issue by kespinola** [holaplex/kubes#16]
## Goal
Document service selection and management for Holaplex API Gateway.

## Tasks
- [x] Document the strategy in [Tech Spec](https://www.notion.so/holaplex/API-Gateway-135623f8fe9c442492328516c36bdde8).
- [x] Devise authentication strategy capable of identify requesters at the API Gateway.

**Comment by mpwsh** [comment]
[API Gateway tech spec](https://www.notion.so/holaplex/API-Gateway-135623f8fe9c442492328516c36bdde8)
