### ISSUE TITLE
Setup Event Bus

### ISSUE THREAD

**Issue by kespinola** [holaplex/kubes#32]
## Goal
Holaplex hub services can publish and subscribe to messages to facilitate communication between services within our network.

## Requirements
- [X] Deploy Red Panda @mpwsh 
- [x] Services have process running that subscribes to messages broadcasted from the message bus @ray-kast 
  - Consumer
  - Producer
  - Schema Registry (Redpanda)
  - Serialization Protobuf
- [X] During local development services can boot a instance of Red Panda so test sending messages and broadcasting them @kespinola @mpwsh

**Comment by mpwsh** [comment]
redpanda has been deployed

**Comment by kespinola** [comment]
@ray-kast subtle difference between redpanda and kafka that he's working through.

**Comment by mpwsh** [comment]
Staging event bus has been exposed through the API Gateway @ `gateway.holaplex.tools:9100` to simplify testing.
Auth is in place as well. Please contact me for creds

**Comment by kespinola** [comment]
https://github.com/holaplex/hub-core
