### ISSUE TITLE
Holaplex Helm Chart Repository

### ISSUE THREAD

**Issue by kespinola** [holaplex/kubes#34]
## Goal

Holaplex can access hub services from a Helm repository.

**Comment by mpwsh** [comment]
We can use github pages for the helm repository. Is that ok? Will make the repo public

**Comment by kespinola** [comment]
> We can use github pages for the helm repository. Is that ok? Will make the repo public

Yeah, that works.

https://helm.sh/docs/topics/chart_repository/#github-pages-example

**Comment by mpwsh** [comment]
helm repo created and working with CI. URL: https://github.com/holaplex/helm-charts

Usage:
```bash
helm repo add holaplex https://holaplex.github.io/helm-charts
helm repo update
```

A custom domain is in the works ( still waiting for SSL): https://charts.holaplex.com

**Comment by kespinola** [comment]
Great job. Ty.
