### ISSUE TITLE
Background Workers for Indexer

### ISSUE THREAD

**Issue by kespinola** [holaplex/kubes#4]
### Goal

A deployment for running background job runner binary.

### Requirements

The argo application for the indexer includes a new deployment for running the job runner binary of the indexer.

**Comment by kespinola** [comment]
Deployment in dev.

https://github.com/holaplex/kubes/commit/6a5635c9065874e920fb027238aacb9033e3cc86

**Comment by mpwsh** [comment]
Deployment in main
[0cd40b6](https://github.com/holaplex/kubes/commit/0cd40b60f2764f643107c1ca188069065effe246)
